### ISSUE TITLE
<style> doesn't work

### ISSUE THREAD

**Issue by karak** [riot/custom-elements#1]
Style section doesn't work because it is just inserted under shadow-root like bellow:

```html
<body>
  <x-hello message="Good-bye!">
     #shadow-root
       <style>x-hello,[data-is="x-hello"]{ color: red; }</style>
       ...
  </x-hello>
</body>
```
Using `:host` rather than custom implementation would fix this.

APPEND:
This issue happened when passing compiled riot.tag, not RAW call of `define`.
For I suppose those use cases would be standard.
...Then,  the compiler should have some CSS switch to support shadow DOM.

**Comment by GianlucaGuarini** [comment]
Fixed in the riot-compiler@3.5.3. Thanks for reporting it

**Comment by karak** [comment]
Thank you. Simple `:host` is OK, but complex selector is still wrong.

```css
    :host {
      color: red;
    }
    .clicked {
      font-weight: bold;
    }
```

is compiled to:

```css
:host { color: red; } x-hello .clicked, [data-is="x-hello"] .clicked{ font-weight: bold; }
```

**Comment by karak** [comment]
I think riot-compiler v3 cannot accept both of light and shadow DOMs without any _switch_ as long as it always transforms CSS, although that switching would be easy by using `::shadow` pseudo selector. 
 And riot@4 work is much preferred, even if only for the custom elements.

**Comment by GianlucaGuarini** [comment]
I can add an option to avoid the scoped behavior. I will check it asap

**Comment by GianlucaGuarini** [comment]
The new `riot-compiler@3.6` has an option to avoid prefixing the css:

```js
const compiler = require('riot-compiler')

compiler.compile(tag, {
  parserOptions: {
    style: {
      prefixCSS: false
    }
  }
}, filePath)
```
